# Generated by Django 4.1.5 on 2025-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
