# Generated by Django 4.1.5 on 2025-02-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0007_remove_assignment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='abacus_app.course'),
            preserve_default=False,
        ),
    ]
