# Generated by Django 5.1.6 on 2025-03-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0008_assignment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ebooks/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to='abacus_app.course')),
            ],
        ),
    ]
