# Generated by Django 5.1.6 on 2025-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0010_ebookpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
            preserve_default=False,
        ),
    ]
