# Generated by Django 5.1.6 on 2025-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0015_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='for_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
