# Generated by Django 5.1.6 on 2025-03-08 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0017_test_result_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_option',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='num_items_per_question',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='test',
            name='num_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='test',
            name='range_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='test',
            name='range_min',
            field=models.IntegerField(default=-10),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
