# Generated by Django 5.1.6 on 2025-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0019_testpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpayment',
            name='amount',
            field=models.CharField(default=300, max_length=255),
            preserve_default=False,
        ),
    ]
