# Generated by Django 5.1.6 on 2025-03-10 09:26

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0020_testpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='operations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('*', 'Multiplication'), ('/', 'Division')], default='+', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.FloatField(),
        ),
    ]
