# Generated by Django 5.1.6 on 2025-03-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0022_studenttestattempt_test_time_self_question_time_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_time_self',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='abacus_app.test_time_self'),
        ),
    ]
