# Generated by Django 5.1.6 on 2025-03-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0023_alter_question_time_self_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacus_app.test_time_self'),
        ),
    ]
