# Generated by Django 5.1.6 on 2025-03-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0024_alter_studenttestattempt_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestattempt',
            name='time_taken',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
