# Generated by Django 5.1.6 on 2025-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0025_studenttestattempt_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
