# Generated by Django 5.1.6 on 2025-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacus_app', '0026_test_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
